name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.5.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  collection: ^1.17.2
  equatable: ^2.0.5
  xml2json: ^6.2.0
  http: ^1.1.0
  rxdart: ^0.28.0
  xml: ^6.3.0
  uuid: ^4.0.0
  postgres: ^2.6.2
  logger: ^2.0.2
  encrypt: ^5.0.3
  yookassa_payments_flutter: ^1.5.0
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.2.2
  lecle_downloads_path_provider: ^0.0.2+8
  fast_immutable_collections: ^10.2.1
  package_info_plus: ^8.0.0

dev_dependencies:
  dart_code_metrics_presets: ^2.3.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter: