name: avtovas_web
description: Автовокзал Чебоксары. Расписание автобусов с автовокзалов и автостанций Чувашской Республики с указанием цены билета, наличия свободных мест и времени
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  flutter_web_plugins:
    sdk: flutter
  common:
    path: ../common
  cupertino_icons: ^1.0.2
  core:
    path: ../core
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  flutter_expandable_fab: ^2.0.0
  back_button_interceptor: ^7.0.0
  equatable: 2.0.5
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  country_code_picker: ^3.0.0
  easy_autocomplete: ^1.6.0
  fast_immutable_collections: ^10.2.1
  postgres: ^2.6.2
  collection: ^1.17.2
  bot_toast: ^4.1.3
  go_router: ^10.2.0
  # cloud_firestore: ^4.12.2
  universal_html: ^2.2.4
  pdf: ^3.10.4
  mailer: ^6.0.1
  intl: ^0.19.0
  webview_flutter_platform_interface: ^2.0.0
  webview_flutter_web: ^0.2.2+3
  app_links: ^3.4.5
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  scroll_to_index: ^3.0.1
  date_picker_plus: ^2.1.0
  flutter_native_splash: ^2.3.10
  cloud_firestore: ^4.17.2

dev_dependencies:
  dart_code_metrics_presets: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vector/
    - assets/animations/
    - assets/captcha_images/
    - assets/app_logo/
  
  fonts:
    - family: Avtovas
      fonts:
        - asset: assets/fonts/Avtovas_Normal.ttf
          style: normal
        - asset: assets/fonts/Avtovas_Bold.ttf
          weight: 500
        - asset: assets/fonts/Avtovas_W_700.ttf
          weight: 700
        - asset: assets/fonts/Avtovas_Italic.ttf
          style: italic
