name: common
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.5.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  core:
    path: ../core
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  get_it: 7.6.4
  go_router: ^10.1.2
  flutter_masked_text2: ^0.9.1
  intl: ^0.19.0
  field_suggestion: ^0.2.5
  shimmer: ^3.0.0
  country_code_picker: ^3.0.0
  pdf: ^3.11.1
  universal_html: ^2.2.4
  rxdart: ^0.27.7

dev_dependencies:
  dart_code_metrics_presets: ^2.3.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:

  generate: true

  assets:
    - assets/vector/

  fonts:
    - family: Avtovas
      fonts:
        - asset: assets/fonts/Avtovas_Normal.ttf
          style: normal
        - asset: assets/fonts/Avtovas_Bold.ttf
          weight: 500
        - asset: assets/fonts/Avtovas_W_700.ttf
          weight: 700
        - asset: assets/fonts/Avtovas_Italic.ttf
          style: italic

