name: avtovas_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+36

environment:
  sdk: ^3.8.0

dependencies:

  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  dio: ^5.8.0+1
  logger: ^2.5.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  dio_smart_retry: ^7.0.1
  flutter_riverpod: ^2.6.1
  rxdart: ^0.28.0
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.1.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  country_code_picker: ^3.3.0
  pinput: ^5.0.1
  scroll_to_index: ^3.0.1
  flutter_keyboard_visibility: ^6.0.0
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed_lint: ^0.0.9
  custom_lint: ^0.7.5
  very_good_analysis: ^7.0.0
  riverpod_lint: ^2.6.5

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/app_logo/avtovas_logo.png
    - assets/vector/
    - assets/images/

  fonts:
    - family: Avtovas
      fonts:
        - asset: assets/fonts/Avtovas_Normal.ttf
          style: normal
        - asset: assets/fonts/Avtovas_Bold.ttf
          weight: 500
        - asset: assets/fonts/Avtovas_W_700.ttf
          weight: 700
        - asset: assets/fonts/Avtovas_Italic.ttf
          style: italic