name: Deploy

on:
  push:
    branches: 
      - dev
    paths:
      - 'avtovas_web/**'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install latest flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          cache: true

      - name: Initialize
        run: |
          cd avtovas_web/
          flutter pub get
          flutter config --enable-web

      - name: Build
        run: |
          cd avtovas_web/
          flutter build web --web-browser-flag "--disable-web-security"
          sed -i 's+href="/"+href="./"+g' build/web/index.html

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: deploy
          folder: avtovas_web/build/web
          clean: true